# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui/config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigDialog(object):
    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.resize(932, 627)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(ConfigDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 821, 551))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.spnTensaoMin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.spnTensaoMin.setObjectName("spnTensaoMin")
        self.verticalLayout_6.addWidget(self.spnTensaoMin)
        self.spnTensaoMax = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.spnTensaoMax.setObjectName("spnTensaoMax")
        self.verticalLayout_6.addWidget(self.spnTensaoMax)
        self.spnIntervalo = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.spnIntervalo.setObjectName("spnIntervalo")
        self.verticalLayout_6.addWidget(self.spnIntervalo)
        self.spnCorrenteMax = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.spnCorrenteMax.setObjectName("spnCorrenteMax")
        self.verticalLayout_6.addWidget(self.spnCorrenteMax)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dateInicio = QtWidgets.QDateEdit(self.verticalLayoutWidget_2)
        self.dateInicio.setObjectName("dateInicio")
        self.horizontalLayout_3.addWidget(self.dateInicio)
        self.cmbPeriodo = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.cmbPeriodo.setObjectName("cmbPeriodo")
        self.horizontalLayout_3.addWidget(self.cmbPeriodo)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfigDialog)
        self.buttonBox.setGeometry(QtCore.QRect(470, 470, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(ConfigDialog)
        QtCore.QMetaObject.connectSlotsByName(ConfigDialog)

    def retranslateUi(self, ConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigDialog.setWindowTitle(_translate("ConfigDialog", "Dialog"))
