# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui/config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.spnTensaoMin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.spnTensaoMin.setObjectName("spnTensaoMin")
        self.verticalLayout.addWidget(self.spnTensaoMin)
        self.spnTensaoMax = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.spnTensaoMax.setObjectName("spnTensaoMax")
        self.verticalLayout.addWidget(self.spnTensaoMax)
        self.spnIntervalo = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.spnIntervalo.setObjectName("spnIntervalo")
        self.verticalLayout.addWidget(self.spnIntervalo)
        self.spnCorrenteMax = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.spnCorrenteMax.setObjectName("spnCorrenteMax")
        self.verticalLayout.addWidget(self.spnCorrenteMax)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget_2)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.cmbPeriodo = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.cmbPeriodo.setObjectName("cmbPeriodo")
        self.horizontalLayout.addWidget(self.cmbPeriodo)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget_2)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
