# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 181, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTensaoValor = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblTensaoValor.setObjectName("lblTensaoValor")
        self.verticalLayout.addWidget(self.lblTensaoValor)
        self.lblPotenciaValor = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblPotenciaValor.setObjectName("lblPotenciaValor")
        self.verticalLayout.addWidget(self.lblPotenciaValor)
        self.lblCorrenteValor = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblCorrenteValor.setObjectName("lblCorrenteValor")
        self.verticalLayout.addWidget(self.lblCorrenteValor)
        self.lblStatusDisjuntor = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblStatusDisjuntor.setObjectName("lblStatusDisjuntor")
        self.verticalLayout.addWidget(self.lblStatusDisjuntor)
        self.lblQualidade = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblQualidade.setObjectName("lblQualidade")
        self.verticalLayout.addWidget(self.lblQualidade)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(180, 0, 621, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.widget = PlotWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(180, 250, 621, 231))
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 480, 801, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 181, 31))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTensaoValor.setText(_translate("MainWindow", "lblTensaoValor"))
        self.lblPotenciaValor.setText(_translate("MainWindow", "lblStatusDisjuntor"))
        self.lblCorrenteValor.setText(_translate("MainWindow", "lblCorrenteValor"))
        self.lblStatusDisjuntor.setText(_translate("MainWindow", "lblPotenciaValor"))
        self.lblQualidade.setText(_translate("MainWindow", "lblQualidade"))
        self.pushButton.setText(_translate("MainWindow", "Alternar Disjuntor"))
        self.pushButton_2.setText(_translate("MainWindow", "Configuracoes"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">STATUS:</p></body></html>"))
from pyqtgraph import PlotWidget
