# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 480, 801, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAlternarDisjuntor = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnAlternarDisjuntor.setObjectName("btnAlternarDisjuntor")
        self.horizontalLayout.addWidget(self.btnAlternarDisjuntor)
        self.btnConfiguracoes = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnConfiguracoes.setObjectName("btnConfiguracoes")
        self.horizontalLayout.addWidget(self.btnConfiguracoes)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 0, 591, 481))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tblEventos = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tblEventos.setObjectName("tblEventos")
        self.tblEventos.setColumnCount(0)
        self.tblEventos.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tblEventos)
        self.graficoConsumo = PlotWidget(self.verticalLayoutWidget_2)
        self.graficoConsumo.setObjectName("graficoConsumo")
        self.verticalLayout_2.addWidget(self.graficoConsumo)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 211, 481))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txtCorrenteValor = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.txtCorrenteValor.setObjectName("txtCorrenteValor")
        self.verticalLayout_3.addWidget(self.txtCorrenteValor)
        self.txtPotenciaValor = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.txtPotenciaValor.setObjectName("txtPotenciaValor")
        self.verticalLayout_3.addWidget(self.txtPotenciaValor)
        self.txtCorrenteValor_4 = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.txtCorrenteValor_4.setObjectName("txtCorrenteValor_4")
        self.verticalLayout_3.addWidget(self.txtCorrenteValor_4)
        self.txtCorrenteValor_3 = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.txtCorrenteValor_3.setObjectName("txtCorrenteValor_3")
        self.verticalLayout_3.addWidget(self.txtCorrenteValor_3)
        self.txtCorrenteValor_2 = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.txtCorrenteValor_2.setObjectName("txtCorrenteValor_2")
        self.verticalLayout_3.addWidget(self.txtCorrenteValor_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblPotenciaValor = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblPotenciaValor.setObjectName("lblPotenciaValor")
        self.verticalLayout.addWidget(self.lblPotenciaValor)
        self.lblTensaoValor = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblTensaoValor.setObjectName("lblTensaoValor")
        self.verticalLayout.addWidget(self.lblTensaoValor)
        self.lblCorrenteValor = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblCorrenteValor.setObjectName("lblCorrenteValor")
        self.verticalLayout.addWidget(self.lblCorrenteValor)
        self.lblStatusDisjuntor = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblStatusDisjuntor.setObjectName("lblStatusDisjuntor")
        self.verticalLayout.addWidget(self.lblStatusDisjuntor)
        self.lblQualidade = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblQualidade.setObjectName("lblQualidade")
        self.verticalLayout.addWidget(self.lblQualidade)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAlternarDisjuntor.setText(_translate("MainWindow", "Alternar Disjuntor"))
        self.btnConfiguracoes.setText(_translate("MainWindow", "Configuracoes"))
        self.txtCorrenteValor.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">STATUS DISJUNTOR:</p></body></html>"))
        self.txtPotenciaValor.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TENSÃO(V):</p></body></html>"))
        self.txtCorrenteValor_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CORRENTE(A):</p></body></html>"))
        self.txtCorrenteValor_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">POTENCIA(W):</p></body></html>"))
        self.txtCorrenteValor_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">QUALIDADE:</p></body></html>"))
        self.lblPotenciaValor.setText(_translate("MainWindow", "lblStatusDisjuntor"))
        self.lblTensaoValor.setText(_translate("MainWindow", "lblTensaoValor"))
        self.lblCorrenteValor.setText(_translate("MainWindow", "lblCorrenteValor"))
        self.lblStatusDisjuntor.setText(_translate("MainWindow", "lblPotenciaValor"))
        self.lblQualidade.setText(_translate("MainWindow", "lblQualidade"))
from pyqtgraph import PlotWidget
